name: Validar Script
on: [push] # Se ejecuta cada vez que haces push
jobs:
  shellcheck:
    name: Revisar sintaxis de Bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Ejecutar Shellcheck
        run: shellcheck script.sh